### ISSUE TITLE
distort example produces .so file rather then .vst

### ISSUE THREAD

**Issue by clownpriest** [p0nce/dplug#72]
I'm on a Mac. Am I doing something wrong?

**Comment by p0nce** [comment]
You are doing nothing wrong.
What I do here is that I have a script that creates the bundle.

See here: http://pastebin.com/j058StjR

I might make it a proper program ouf of this script and put it in the dplug repo.

Note that currently there is multiple caveats associated with using OS X. One user told me plugins don't scan in 10.9

Let me know if it works for you and what is your system.

**Comment by p0nce** [comment]
8c0585a535e896cb6c6cc49cd85291d7e252a6dd

Build the `release` tool in `tools/`, then build the distort example with `release -c dmd` or `release -c ldc` (default)
This will make a bundle with the .so

**Comment by clownpriest** [comment]
i'm on OS X 10.10.4. I tried to build with a dub built from your branch and got this error:
``` bash
./vstscript -c ldc
PATH = /Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/andrei/Downloads/go_appengine:/Users/andrei/code/third_party/ldc-0.15.2b1/bin:/usr/local/bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/texbin:/usr/local/mysql/bin:/usr/local/DCD/bin:/usr/local/go/bin:/Users/andrei/go/bin
Creating directory distort-~master/Mac-OS-X_64-bit_VST_ldc
*** Building with ldc2, 64-bit arch
*** dub build --build=debug --arch=x86_64 --compiler=ldc2   
Performing "debug" build using ldc2 for x86_64.
gfm:core 3.0.4: building configuration "library"...
dplug:core 1.1.30+commit.8.g1e46623: building configuration "library"...
gfm:math 3.0.4: building configuration "library"...
dplug:dsp 1.1.30+commit.8.g1e46623: building configuration "library"...
ae-graphics 0.0.7: building configuration "library"...
dplug:plugin 1.1.30+commit.8.g1e46623: building configuration "library"...
ldc2: for the -march option: may only occur zero or one times!
ldc2 failed with exit code 1.
error: Command 'dub build --build=debug --arch=x86_64 --compiler=ldc2   ' returned 2
```

**Comment by p0nce** [comment]
The problem is that DUB sends multiple `-march` flags: https://github.com/D-Programming-Language/dub/issues/686

If you use LDC and OSX, you need to checkout and build this modified dub: https://github.com/D-Programming-Language/dub/pull/681 
This branch `issue-635-bis` is the one that will interest you, it removes duplicated -march flags, and fix other flags with LDC.

About LDC versions: ldc-0.15.2b1 should be ok but most of my testing was with ldc-0.15.2b2


Note that you can also use DMD to build plugins, which happens to work god know why.

**Comment by clownpriest** [comment]
i just built from the issue-635-bis branch and now it works. thank you!

**Comment by clownpriest** [comment]
Probably not an issue with dplug, but do you know why Ableton will recognize it but Logic Pro X won't? It's most likely some setting I'm not selecting within Logic.

**Comment by clownpriest** [comment]
nevermind, just realized Logic doesn't support VST's

**Comment by p0nce** [comment]
Yes. I haven't looked yet on the AudioUnit SDK. It seems like you need inheritance from C++ classe, that should be doable with enough coffee.
